# -*- coding: utf-8 -*-
"""ObtainingTweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDkWp28Yw7rSvg8u7yZNzmOKqYganNbM
"""

import requests
import os
import json
import csv
import re

# To set your environment variables in your terminal run the following line:
# export 'BEARER_TOKEN'='<your_bearer_token>'
# bearer_token = os.environ.get("BEARER_TOKEN")
bearer_token = ''

search_url = "https://api.twitter.com/2/tweets/search/all"

# Optional params: start_time,end_time,since_id,until_id,max_results,next_token,
# expansions,tweet.fields,media.fields,poll.fields,place.fields,user.fields
query_params = { 'query': 'lang:en place:Delhi',
                'start_time' : '2021-05-18T00:00:00Z', 
                'end_time' : '2021-05-24T23:59:59Z',
                'max_results' : '500'
                #,'place.fields':['country' : 'India','country_code' : 'IN','place_type' : 'city','name' : 'Delhi']
                }


def create_headers(bearer_token):
    headers = {"Authorization": "Bearer {}".format(bearer_token)}
    return headers


def connect_to_endpoint(url, headers, params):
    response = requests.request("GET", search_url, headers=headers, params=params)
    print(response.status_code)
    if response.status_code != 200:
        raise Exception(response.status_code, response.text)
    return response.json()

def clean_tweet(tweet):
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t]) | (\w +:\ / \ / \S +)", " ", tweet).split())

def main():
    headers = create_headers(bearer_token)
    json_response = connect_to_endpoint(search_url, headers, query_params)

    # csv_file = open('week1.csv', 'w')
    text_file = open("/content/drive/MyDrive/CommunityTweets/week61.txt", "w")
    # csv_writer = csv.writer(csv_file)

    all_tweets = []
    for tweet in json_response['data']:
      tweet = clean_tweet(tweet['text'])
      text_file.write("%s\n" % tweet)
      all_tweets.append(tweet)

    text_file.close()
    # csv_writer.writerows(all_tweets)    
    # csv_file.close()
    # print(json.dumps(json_response, indent=4, sort_keys=True))


if __name__ == "__main__":
    main()

